### ISSUE TITLE
Redirect to signin

### ISSUE THREAD

**Issue by kaleming** [testdrivenio/flask-spa-auth#8]
Hi @amalshaji,

First of all, thank you for this very nice tutorial.

I have a question related to login page.

Supposing I try to [localhost:81/api/data](localhost:81/api/data) when I have not been authenticated.

It appear: Unauthorized access.

I am trying to:
1 - redirect to login page
2- after authenticated, redirect to previous request (localhost:81/api/data)

In order to do that, I tried to use this function on app.py:
```
@app.after_request
 def redirect_to_signin(response):
     if response.status_code == 401:
         return redirect(request.host_url + 'auth/signin?next=' + request.url)
```
But it seems this doesn't work, because probably this should be done using javascript ?

Is there a easy way to accomplish it ?

**Comment by mjhea0** [comment]
Yes, handle the redirect on the client.
